package jdt.gui;

import jdt.data.Project;
import jdt.data.User;
import jdt.data.UserCreds;
import jdt.manager.ProjectManager;
import jdt.manager.UserManager;
import jdt.manager.Validator;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import com.github.weisj.darklaf.LafManager;
import com.github.weisj.darklaf.theme.DarculaTheme;
import javax.swing.ImageIcon;

/**
 *
 * @author Luke Leppan
 */
public class MainForm extends javax.swing.JFrame {

	CardLayout cardLayoutMain;
	CardLayout cardLayoutPV;

	public User currentUser;
	public String currentUsername;

	public MainForm() {
		initComponents();

		this.setLocationRelativeTo(null); // Set to Center

		ImageIcon icon = new ImageIcon(getClass().getResource("/jdt/images/logo.png"));
		setIconImage(icon.getImage());

		cardLayoutMain = (CardLayout) (pnlMain.getLayout()); // Get Main card layout
		cardLayoutPV = (CardLayout) (pnlCardPV.getLayout());  // Get PV card layout
	}

	public void refreshProjectView() {  //Loads Project Components for Project View
		ScrollViewPV.removeAll();
		ScrollViewPV.invalidate();
		ScrollViewPV.validate();
		ScrollViewPV.repaint();
		ProjectManager projectManager = new ProjectManager();
		List<Project> projects = projectManager.getUserProjects(currentUser);
		Dimension preferredSize = new Dimension(818, 210 * projects.size() + 10);
		ScrollViewPV.setPreferredSize(preferredSize);
		ProjectScrollViewPV.getVerticalScrollBar().setUnitIncrement(16);
		ProjectScrollViewPV.getVerticalScrollBar().setAutoscrolls(false);

		for (int i = 0; i < projects.size(); i++) {
			Project project = projects.get(i);
			CardLayout cardLayout = this.cardLayoutMain;
			ProjectTile projectTile = new ProjectTile(project, cardLayout, pnlMain);

			projectTile.setSize(395, 202);
			projectTile.setLocation(140, 206 * i + 5);
			projectTile.setVisible(true);

			ScrollViewPV.add(projectTile);
		}

		ScrollViewPV.invalidate();
		ScrollViewPV.validate();
		ScrollViewPV.repaint();
	}

	private void setAccountDetails() {  // Sets the current users details
		AccountName.setText(currentUser.getUserFirstName() + " " + currentUser.getUserSurname());
		AccountUsername.setText(currentUsername);
	}

	private int calcPassScore(String password) { // Calculates the password strength
		int score = 0;

		//Calc Score
		Pattern upperRegex = Pattern.compile("[A-Z]");
		Pattern lowerRegex = Pattern.compile("[a-z]");
		Pattern numberRegex = Pattern.compile("[0-9]");
		Pattern specialRegex = Pattern.compile(".[!,@,#,$,%,^,&,*,?,_,~,-,£,(,)]");
		int minLength = 8;

		Matcher matcher1 = upperRegex.matcher(password);
		if (matcher1.find()) {
			score++;
		}

		Matcher matcher2 = lowerRegex.matcher(password);
		if (matcher2.find()) {
			score++;
		}

		Matcher matcher3 = numberRegex.matcher(password);
		if (matcher3.find()) {
			score++;
		}

		Matcher matcher4 = specialRegex.matcher(password);
		if (matcher4.find()) {
			score++;
		}

		if (score < 3) {
			score--;
		}

		if (password.length() > minLength) {
			score += Math.floor((password.length() - minLength) / 2);
		}

		if (password.length() < minLength) {
			score = 0;
		}

		return score;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlInitial = new javax.swing.JPanel();
        pnlInitialContainer = new javax.swing.JPanel();
        pnlTitleContainer = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlButtonContainer = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlSignIn = new javax.swing.JPanel();
        pnlSignInContainer = new javax.swing.JPanel();
        UsernameText = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        UsernameText2 = new javax.swing.JLabel();
        SignInButtonLogPNL = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        ErrorText = new javax.swing.JLabel();
        SignUpInsteadButtonLogPNL = new javax.swing.JButton();
        pnlProjectList = new javax.swing.JPanel();
        pnlMainSplit = new javax.swing.JSplitPane();
        pnlSidePane = new javax.swing.JPanel();
        AccountPanel = new javax.swing.JPanel();
        AccountName = new javax.swing.JLabel();
        AccountUsername = new javax.swing.JLabel();
        AccountSetButtons = new javax.swing.JButton();
        AccountIcon = new javax.swing.JLabel();
        pnlCardPV = new javax.swing.JPanel();
        ProjectViewCardPV = new javax.swing.JPanel();
        ProjectViewToolBarPV = new javax.swing.JPanel();
        NewProjectButtonPV = new javax.swing.JButton();
        RefreshButtonPV = new javax.swing.JButton();
        ProjectScrollViewPV = new javax.swing.JScrollPane();
        ScrollViewPV = new javax.swing.JPanel();
        NewProjectViewPV = new javax.swing.JPanel();
        NewProjectDetailsPV = new javax.swing.JPanel();
        ProjectNameLabelNPPV = new javax.swing.JLabel();
        ProjectNameTXTNPPV = new javax.swing.JTextField();
        ProjectDescriptionLabelNPPV = new javax.swing.JLabel();
        TextScrollNPPV = new javax.swing.JScrollPane();
        DesriptionTextAreaNPPV = new javax.swing.JTextArea();
        CreateProjectBTNNPPV = new javax.swing.JButton();
        ErrorLabelNPPV = new javax.swing.JLabel();
        ToolBarNPPV = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        SeperatorNPPV = new javax.swing.JSeparator();
        AccountSettingsPanel = new javax.swing.JPanel();
        AccountSettingToolbar = new javax.swing.JPanel();
        AccounSettingsBackButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        DeleteAccountButton = new javax.swing.JButton();
        pnlSignUp = new javax.swing.JPanel();
        pnlSignUpContainer = new javax.swing.JPanel();
        lblFirstNameSignUp = new javax.swing.JLabel();
        txtFirstNameSignUp = new javax.swing.JTextField();
        lblSurnameSignUp = new javax.swing.JLabel();
        txtSurnameSignUp = new javax.swing.JTextField();
        lblUsernameSignUp = new javax.swing.JLabel();
        txtUsernameSignUp = new javax.swing.JTextField();
        lblEmailSignUp = new javax.swing.JLabel();
        txtEmailSignUp = new javax.swing.JTextField();
        lblDOBSignUP = new javax.swing.JLabel();
        lblPasswordSignUp = new javax.swing.JLabel();
        txtPasswordSignUp = new javax.swing.JPasswordField();
        lblPasswordStrengthSignUp = new javax.swing.JLabel();
        pbarPasswordStrengthSignUp = new javax.swing.JProgressBar();
        lblConfirmPasswordSignUp = new javax.swing.JLabel();
        txtConfirmPasswordSignUp = new javax.swing.JPasswordField();
        lblErrorSignUp = new javax.swing.JLabel();
        btnSignUpInsteadSignUp = new javax.swing.JButton();
        btnSignUpSignUp = new javax.swing.JButton();
        dcDOBSignUp = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Just Do It");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        pnlMain.setLayout(new java.awt.CardLayout());

        lblTitle.setFont(new java.awt.Font("Fredoka One", 1, 36)); // NOI18N
        lblTitle.setText("Just Do It");

        lblSubtitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblSubtitle.setText("Project Manager");

        javax.swing.GroupLayout pnlTitleContainerLayout = new javax.swing.GroupLayout(pnlTitleContainer);
        pnlTitleContainer.setLayout(pnlTitleContainerLayout);
        pnlTitleContainerLayout.setHorizontalGroup(
            pnlTitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleContainerLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(lblSubtitle)
                .addGap(47, 47, 47))
        );
        pnlTitleContainerLayout.setVerticalGroup(
            pnlTitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleContainerLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubtitle)
                .addContainerGap())
        );

        btnSignUp.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/add_user.png"))); // NOI18N
        btnSignUp.setText("Sign up");
        btnSignUp.setToolTipText("Click To Sign up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnSignIn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/login.png"))); // NOI18N
        btnSignIn.setText("Sign in");
        btnSignIn.setToolTipText("Click To Sign in");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonContainerLayout = new javax.swing.GroupLayout(pnlButtonContainer);
        pnlButtonContainer.setLayout(pnlButtonContainerLayout);
        pnlButtonContainerLayout.setHorizontalGroup(
            pnlButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonContainerLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pnlButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        pnlButtonContainerLayout.setVerticalGroup(
            pnlButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonContainerLayout.createSequentialGroup()
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInitialContainerLayout = new javax.swing.GroupLayout(pnlInitialContainer);
        pnlInitialContainer.setLayout(pnlInitialContainerLayout);
        pnlInitialContainerLayout.setHorizontalGroup(
            pnlInitialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialContainerLayout.createSequentialGroup()
                .addGroup(pnlInitialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInitialContainerLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(pnlTitleContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInitialContainerLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(pnlButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlInitialContainerLayout.setVerticalGroup(
            pnlInitialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnlTitleContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jButton1.setText("Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInitialLayout = new javax.swing.GroupLayout(pnlInitial);
        pnlInitial.setLayout(pnlInitialLayout);
        pnlInitialLayout.setHorizontalGroup(
            pnlInitialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialLayout.createSequentialGroup()
                .addGroup(pnlInitialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInitialLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(pnlInitialContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInitialLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        pnlInitialLayout.setVerticalGroup(
            pnlInitialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(pnlInitialContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pnlMain.add(pnlInitial, "InitialPanel");

        pnlSignInContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N

        UsernameText.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText.setText("Username");

        UsernameField.setToolTipText("Enter your Username");

        UsernameText2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        UsernameText2.setText("Password");

        SignInButtonLogPNL.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        SignInButtonLogPNL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/login.png"))); // NOI18N
        SignInButtonLogPNL.setText("Sign in");
        SignInButtonLogPNL.setToolTipText("Click To Sign in");
        SignInButtonLogPNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonLogPNLActionPerformed(evt);
            }
        });

        PasswordField.setToolTipText("Enter Password");

        ErrorText.setForeground(new java.awt.Color(255, 0, 51));

        SignUpInsteadButtonLogPNL.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        SignUpInsteadButtonLogPNL.setText("Sign Up Instead");
        SignUpInsteadButtonLogPNL.setToolTipText("Click to Sign Up");
        SignUpInsteadButtonLogPNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpInsteadButtonLogPNLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSignInContainerLayout = new javax.swing.GroupLayout(pnlSignInContainer);
        pnlSignInContainer.setLayout(pnlSignInContainerLayout);
        pnlSignInContainerLayout.setHorizontalGroup(
            pnlSignInContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignInContainerLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignInContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSignInContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PasswordField)
                    .addComponent(UsernameField)
                    .addGroup(pnlSignInContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlSignInContainerLayout.createSequentialGroup()
                            .addComponent(SignUpInsteadButtonLogPNL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SignInButtonLogPNL))
                        .addComponent(UsernameText2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UsernameText, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(39, 39, 39))
        );
        pnlSignInContainerLayout.setVerticalGroup(
            pnlSignInContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignInContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(UsernameText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSignInContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignInButtonLogPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SignUpInsteadButtonLogPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(266, 266, 266)
                .addComponent(ErrorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSignInLayout = new javax.swing.GroupLayout(pnlSignIn);
        pnlSignIn.setLayout(pnlSignInLayout);
        pnlSignInLayout.setHorizontalGroup(
            pnlSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignInLayout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(pnlSignInContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        pnlSignInLayout.setVerticalGroup(
            pnlSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignInLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(pnlSignInContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pnlMain.add(pnlSignIn, "LoginPanel");

        pnlMainSplit.setDividerSize(2);

        pnlSidePane.setEnabled(false);
        pnlSidePane.setPreferredSize(new java.awt.Dimension(200, 0));

        AccountName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        AccountName.setText("John Doe");
        AccountName.setMaximumSize(new java.awt.Dimension(73, 15));
        AccountName.setMinimumSize(new java.awt.Dimension(73, 15));
        AccountName.setPreferredSize(new java.awt.Dimension(73, 15));

        AccountUsername.setText("johndoe");

        AccountSetButtons.setText("Account Settings");
        AccountSetButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountSetButtonsActionPerformed(evt);
            }
        });

        AccountIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/account.png"))); // NOI18N

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addComponent(AccountIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccountName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccountUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccountSetButtons)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addComponent(AccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountUsername))
                    .addComponent(AccountIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AccountSetButtons)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSidePaneLayout = new javax.swing.GroupLayout(pnlSidePane);
        pnlSidePane.setLayout(pnlSidePaneLayout);
        pnlSidePaneLayout.setHorizontalGroup(
            pnlSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSidePaneLayout.setVerticalGroup(
            pnlSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidePaneLayout.createSequentialGroup()
                .addGap(0, 512, Short.MAX_VALUE)
                .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMainSplit.setLeftComponent(pnlSidePane);

        pnlCardPV.setPreferredSize(new java.awt.Dimension(670, 578));
        pnlCardPV.setLayout(new java.awt.CardLayout());

        ProjectViewCardPV.setPreferredSize(new java.awt.Dimension(620, 578));
        ProjectViewCardPV.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ProjectViewCardPVComponentAdded(evt);
            }
        });
        ProjectViewCardPV.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProjectViewCardPVComponentShown(evt);
            }
        });

        NewProjectButtonPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/add.png"))); // NOI18N
        NewProjectButtonPV.setText("New Project");
        NewProjectButtonPV.setToolTipText("Click to create new project");
        NewProjectButtonPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProjectButtonPVActionPerformed(evt);
            }
        });

        RefreshButtonPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/refresh.png"))); // NOI18N
        RefreshButtonPV.setText("Refresh");
        RefreshButtonPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonPVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProjectViewToolBarPVLayout = new javax.swing.GroupLayout(ProjectViewToolBarPV);
        ProjectViewToolBarPV.setLayout(ProjectViewToolBarPVLayout);
        ProjectViewToolBarPVLayout.setHorizontalGroup(
            ProjectViewToolBarPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectViewToolBarPVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewProjectButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefreshButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProjectViewToolBarPVLayout.setVerticalGroup(
            ProjectViewToolBarPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectViewToolBarPVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectViewToolBarPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewProjectButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshButtonPV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ProjectScrollViewPV.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ProjectScrollViewPV.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout ScrollViewPVLayout = new javax.swing.GroupLayout(ScrollViewPV);
        ScrollViewPV.setLayout(ScrollViewPVLayout);
        ScrollViewPVLayout.setHorizontalGroup(
            ScrollViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        ScrollViewPVLayout.setVerticalGroup(
            ScrollViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        ProjectScrollViewPV.setViewportView(ScrollViewPV);

        javax.swing.GroupLayout ProjectViewCardPVLayout = new javax.swing.GroupLayout(ProjectViewCardPV);
        ProjectViewCardPV.setLayout(ProjectViewCardPVLayout);
        ProjectViewCardPVLayout.setHorizontalGroup(
            ProjectViewCardPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectViewCardPVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectViewCardPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectScrollViewPV, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addGroup(ProjectViewCardPVLayout.createSequentialGroup()
                        .addComponent(ProjectViewToolBarPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        ProjectViewCardPVLayout.setVerticalGroup(
            ProjectViewCardPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectViewCardPVLayout.createSequentialGroup()
                .addComponent(ProjectViewToolBarPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectScrollViewPV))
        );

        pnlCardPV.add(ProjectViewCardPV, "ProjectViewPV");

        NewProjectDetailsPV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create New Project", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 16))); // NOI18N

        ProjectNameLabelNPPV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ProjectNameLabelNPPV.setText("Project Title");

        ProjectDescriptionLabelNPPV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ProjectDescriptionLabelNPPV.setText("Project Description");

        DesriptionTextAreaNPPV.setColumns(20);
        DesriptionTextAreaNPPV.setLineWrap(true);
        DesriptionTextAreaNPPV.setRows(5);
        TextScrollNPPV.setViewportView(DesriptionTextAreaNPPV);

        CreateProjectBTNNPPV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/add.png"))); // NOI18N
        CreateProjectBTNNPPV.setText("Create");
        CreateProjectBTNNPPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProjectBTNNPPVActionPerformed(evt);
            }
        });

        ErrorLabelNPPV.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ErrorLabelNPPV.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout NewProjectDetailsPVLayout = new javax.swing.GroupLayout(NewProjectDetailsPV);
        NewProjectDetailsPV.setLayout(NewProjectDetailsPVLayout);
        NewProjectDetailsPVLayout.setHorizontalGroup(
            NewProjectDetailsPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewProjectDetailsPVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateProjectBTNNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(NewProjectDetailsPVLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(NewProjectDetailsPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProjectDescriptionLabelNPPV)
                    .addComponent(ProjectNameLabelNPPV)
                    .addGroup(NewProjectDetailsPVLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ErrorLabelNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ProjectNameTXTNPPV)
                    .addComponent(TextScrollNPPV))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        NewProjectDetailsPVLayout.setVerticalGroup(
            NewProjectDetailsPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewProjectDetailsPVLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ProjectNameLabelNPPV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectNameTXTNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProjectDescriptionLabelNPPV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextScrollNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabelNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(CreateProjectBTNNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/back_green.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToolBarNPPVLayout = new javax.swing.GroupLayout(ToolBarNPPV);
        ToolBarNPPV.setLayout(ToolBarNPPVLayout);
        ToolBarNPPVLayout.setHorizontalGroup(
            ToolBarNPPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarNPPVLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BackButton)
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(ToolBarNPPVLayout.createSequentialGroup()
                .addComponent(SeperatorNPPV)
                .addContainerGap())
        );
        ToolBarNPPVLayout.setVerticalGroup(
            ToolBarNPPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolBarNPPVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeperatorNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout NewProjectViewPVLayout = new javax.swing.GroupLayout(NewProjectViewPV);
        NewProjectViewPV.setLayout(NewProjectViewPVLayout);
        NewProjectViewPVLayout.setHorizontalGroup(
            NewProjectViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBarNPPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NewProjectViewPVLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(NewProjectDetailsPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewProjectViewPVLayout.setVerticalGroup(
            NewProjectViewPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewProjectViewPVLayout.createSequentialGroup()
                .addComponent(ToolBarNPPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(NewProjectDetailsPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pnlCardPV.add(NewProjectViewPV, "NewProject");

        AccounSettingsBackButton.setText("Back");
        AccounSettingsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccounSettingsBackButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Account Settings");

        javax.swing.GroupLayout AccountSettingToolbarLayout = new javax.swing.GroupLayout(AccountSettingToolbar);
        AccountSettingToolbar.setLayout(AccountSettingToolbarLayout);
        AccountSettingToolbarLayout.setHorizontalGroup(
            AccountSettingToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountSettingToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccounSettingsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        AccountSettingToolbarLayout.setVerticalGroup(
            AccountSettingToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccountSettingToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccountSettingToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccounSettingsBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DeleteAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/delete.png"))); // NOI18N
        DeleteAccountButton.setText("Delete Account");
        DeleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(DeleteAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(249, 249, 249))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(DeleteAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout AccountSettingsPanelLayout = new javax.swing.GroupLayout(AccountSettingsPanel);
        AccountSettingsPanel.setLayout(AccountSettingsPanelLayout);
        AccountSettingsPanelLayout.setHorizontalGroup(
            AccountSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccountSettingToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AccountSettingsPanelLayout.setVerticalGroup(
            AccountSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountSettingsPanelLayout.createSequentialGroup()
                .addComponent(AccountSettingToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCardPV.add(AccountSettingsPanel, "AccountSettings");

        pnlMainSplit.setRightComponent(pnlCardPV);

        javax.swing.GroupLayout pnlProjectListLayout = new javax.swing.GroupLayout(pnlProjectList);
        pnlProjectList.setLayout(pnlProjectListLayout);
        pnlProjectListLayout.setHorizontalGroup(
            pnlProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainSplit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        pnlProjectListLayout.setVerticalGroup(
            pnlProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainSplit, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnlMain.add(pnlProjectList, "ProjectView");

        pnlSignUpContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign Up", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N
        pnlSignUpContainer.setNextFocusableComponent(txtUsernameSignUp);

        lblFirstNameSignUp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblFirstNameSignUp.setLabelFor(txtFirstNameSignUp);
        lblFirstNameSignUp.setText("First Name");

        txtFirstNameSignUp.setToolTipText("Enter First Name");
        txtFirstNameSignUp.setNextFocusableComponent(txtSurnameSignUp);

        lblSurnameSignUp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblSurnameSignUp.setLabelFor(txtSurnameSignUp);
        lblSurnameSignUp.setText("Surname");

        txtSurnameSignUp.setToolTipText("Enter Surname");
        txtSurnameSignUp.setNextFocusableComponent(txtUsernameSignUp);

        lblUsernameSignUp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblUsernameSignUp.setLabelFor(UsernameField);
        lblUsernameSignUp.setText("Username");

        txtUsernameSignUp.setToolTipText("Enter Username");
        txtUsernameSignUp.setNextFocusableComponent(txtEmailSignUp);

        lblEmailSignUp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblEmailSignUp.setLabelFor(txtEmailSignUp);
        lblEmailSignUp.setText("Email");

        txtEmailSignUp.setToolTipText("Enter Email");

        lblDOBSignUP.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblDOBSignUP.setText("Date Of Birth");

        lblPasswordSignUp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblPasswordSignUp.setLabelFor(txtPasswordSignUp);
        lblPasswordSignUp.setText("Password");

        txtPasswordSignUp.setToolTipText("Enter Password");
        txtPasswordSignUp.setNextFocusableComponent(txtConfirmPasswordSignUp);
        txtPasswordSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordSignUpMouseClicked(evt);
            }
        });
        txtPasswordSignUp.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPasswordSignUpInputMethodTextChanged(evt);
            }
        });
        txtPasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordSignUpActionPerformed(evt);
            }
        });
        txtPasswordSignUp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPasswordSignUpPropertyChange(evt);
            }
        });
        txtPasswordSignUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordSignUpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordSignUpKeyTyped(evt);
            }
        });

        lblPasswordStrengthSignUp.setLabelFor(pbarPasswordStrengthSignUp);
        lblPasswordStrengthSignUp.setText("Password Strength");

        lblConfirmPasswordSignUp.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblConfirmPasswordSignUp.setLabelFor(txtConfirmPasswordSignUp);
        lblConfirmPasswordSignUp.setText("Confirm Password");

        txtConfirmPasswordSignUp.setToolTipText("Renter Password");
        txtConfirmPasswordSignUp.setNextFocusableComponent(btnSignUpSignUp);
        txtConfirmPasswordSignUp.setOpaque(false);

        lblErrorSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblErrorSignUp.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorSignUp.setAutoscrolls(true);
        lblErrorSignUp.setFocusable(false);

        btnSignUpInsteadSignUp.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnSignUpInsteadSignUp.setText("Sign In Instead");
        btnSignUpInsteadSignUp.setToolTipText("Click to switch to Login");
        btnSignUpInsteadSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpInsteadSignUpActionPerformed(evt);
            }
        });

        btnSignUpSignUp.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        btnSignUpSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdt/images/add_user.png"))); // NOI18N
        btnSignUpSignUp.setText("Sign up");
        btnSignUpSignUp.setToolTipText("Click To Sign up");
        btnSignUpSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSignUpContainerLayout = new javax.swing.GroupLayout(pnlSignUpContainer);
        pnlSignUpContainer.setLayout(pnlSignUpContainerLayout);
        pnlSignUpContainerLayout.setHorizontalGroup(
            pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                .addGroup(pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnSignUpInsteadSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignUpSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                                .addGroup(pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEmailSignUp)
                                    .addComponent(lblUsernameSignUp)
                                    .addComponent(lblSurnameSignUp)
                                    .addComponent(lblFirstNameSignUp)
                                    .addComponent(txtUsernameSignUp)
                                    .addComponent(txtSurnameSignUp)
                                    .addComponent(txtFirstNameSignUp)
                                    .addComponent(txtEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblConfirmPasswordSignUp)
                                    .addComponent(lblPasswordSignUp)
                                    .addComponent(lblDOBSignUP)
                                    .addComponent(txtPasswordSignUp)
                                    .addComponent(txtConfirmPasswordSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(pbarPasswordStrengthSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(lblPasswordStrengthSignUp)
                                    .addComponent(dcDOBSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlSignUpContainerLayout.setVerticalGroup(
            pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                        .addComponent(lblFirstNameSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstNameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSurnameSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSurnameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsernameSignUp))
                    .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                        .addComponent(lblDOBSignUP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcDOBSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPasswordSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPasswordStrengthSignUp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                        .addComponent(txtUsernameSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblEmailSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSignUpContainerLayout.createSequentialGroup()
                        .addComponent(pbarPasswordStrengthSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblConfirmPasswordSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConfirmPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblErrorSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSignUpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSignUpInsteadSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignUpSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSignUpLayout = new javax.swing.GroupLayout(pnlSignUp);
        pnlSignUp.setLayout(pnlSignUpLayout);
        pnlSignUpLayout.setHorizontalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(pnlSignUpContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        pnlSignUpLayout.setVerticalGroup(
            pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnlSignUpContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pnlMain.add(pnlSignUp, "RegisterPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
		cardLayoutMain.show(pnlMain, "RegisterPanel");  // Switch to Register View
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
		cardLayoutMain.show(pnlMain, "LoginPanel");  // Switch to Login View
    }//GEN-LAST:event_btnSignInActionPerformed

        private void SignInButtonLogPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonLogPNLActionPerformed
		// Sign In Logic

		UserManager userManager = new UserManager();
		if (userManager.loginUser(UsernameField.getText(), new String(PasswordField.getPassword()))) {
			currentUsername = UsernameField.getText();
			currentUser = userManager.getUser(currentUsername);
			cardLayoutMain.show(pnlMain, "ProjectView");
			refreshProjectView();
			setAccountDetails();
			JOptionPane.showMessageDialog(this,
							"✔ Successful Login"
							+ "\nWelcome " + currentUser.getUserFirstName()
			);
		} else {
			JOptionPane.showMessageDialog(this,
							"❌ Username or Password is Incorrect"
							+ "\nPlease Try Again"
			);
		}
        }//GEN-LAST:event_SignInButtonLogPNLActionPerformed

        private void SignUpInsteadButtonLogPNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpInsteadButtonLogPNLActionPerformed
		cardLayoutMain.show(pnlMain, "RegisterPanel"); //Switch to Register Panel
        }//GEN-LAST:event_SignUpInsteadButtonLogPNLActionPerformed

        private void btnSignUpSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpSignUpActionPerformed
		// Sign In Logic

		lblErrorSignUp.setText("");
		String firstname = txtFirstNameSignUp.getText();
		String surname = txtSurnameSignUp.getText();
		String username = txtUsernameSignUp.getText();
		String email = txtEmailSignUp.getText();
		Date DOB = dcDOBSignUp.getDate();
		char[] password = txtPasswordSignUp.getPassword();
		char[] repeatPassword = txtConfirmPasswordSignUp.getPassword();

		char[] tempPassword = txtPasswordSignUp.getPassword();
		String passwordStr = "";

		User user = new User(0, email, DOB, firstname, surname);
		UserCreds userCreds = new UserCreds(0, username, new String(password));

		for (int i = 0; i < tempPassword.length; i++) {
			passwordStr = passwordStr + tempPassword[i];
		}

		int passScore = calcPassScore(passwordStr);

		Validator validator = new Validator(firstname, surname, username, email, DOB, password, repeatPassword, passScore);
		String errorText = "";

		UserManager userManager = new UserManager();

		// Use Validator
		if (!validator.validateFirstname()) {
			errorText = "Please Enter your First Name.";
		} else if (!validator.validateFirstnameLength()) {
			errorText = "First Name is too long. Must be 100 or less characters.";
		} else if (!validator.validateSurname()) {
			errorText = "Please Enter your Surname.";
		} else if (!validator.validateSurnameLength()) {
			errorText = "Surname is too long. Must be 100 or less characters.";
		} else if (!validator.validateUsername()) {
			errorText = "Username does not follow correct format. Check the help for more information.";
		} else if (!validator.validateUsernameLength()) {
			errorText = "Username is too long. Must be 25 or less characters.";
		} else if (!validator.validateEmail()) {
			errorText = "Not a valid Email";
		} else if (!validator.validateEmailLength()) {
			errorText = "Email is too long. Must be 255 or less characters.";
		} else if (!validator.validateDOB()) {
			errorText = "Please Select your date of Birth.";
		} else if (!validator.validateDOBLogic()) {
			errorText = "Date of birth is in the future.";
		} else if (!validator.validatePasswordMatch()) {
			errorText = "Passwords do not match.";
		} else if (!validator.validatePasswordLength()) {
			errorText = "Password is too short. Must be greater than 8 characters.";
		} else if (!validator.validatePasswordStrength()) {
			errorText = "Your password is not strong enough. Try adding numbers or special charaters.";
		} else if (userManager.checkForUser(username)) {
			errorText = "Username is already taken.";
		} else if (userManager.registerUser(user, userCreds)) {
			cardLayoutMain.show(pnlMain, "LoginPanel");
			JOptionPane.showMessageDialog(this,
							"Successfully Registered ✔"
							+ "\nPlease Login"
			);
		}

		lblErrorSignUp.setText(errorText);

        }//GEN-LAST:event_btnSignUpSignUpActionPerformed

        private void btnSignUpInsteadSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpInsteadSignUpActionPerformed
		cardLayoutMain.show(pnlMain, "LoginPanel"); // Switch to Login Panel
        }//GEN-LAST:event_btnSignUpInsteadSignUpActionPerformed

  private void txtPasswordSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordSignUpMouseClicked
		// TODO add your handling code here:
  }//GEN-LAST:event_txtPasswordSignUpMouseClicked

  private void txtPasswordSignUpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordSignUpKeyTyped
		char[] tempPassword = txtPasswordSignUp.getPassword();
		String password = "";

		for (int i = 0; i < tempPassword.length; i++) {
			password = password + tempPassword[i];
		}

		password = password + evt.getKeyChar();

		int score = calcPassScore(password);

		if (score == 0) {
			pbarPasswordStrengthSignUp.setValue(5);
		} else if (score < 3) {
			pbarPasswordStrengthSignUp.setValue(20);
		} else if (score < 4) {
			pbarPasswordStrengthSignUp.setValue(50);
		} else if (score < 6) {
			pbarPasswordStrengthSignUp.setValue(70);
		} else {
			pbarPasswordStrengthSignUp.setValue(100);
		}

  }//GEN-LAST:event_txtPasswordSignUpKeyTyped

  private void txtPasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordSignUpActionPerformed
		// TODO add your handling code here:
  }//GEN-LAST:event_txtPasswordSignUpActionPerformed

  private void txtPasswordSignUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordSignUpKeyPressed

  }//GEN-LAST:event_txtPasswordSignUpKeyPressed

  private void txtPasswordSignUpInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPasswordSignUpInputMethodTextChanged

  }//GEN-LAST:event_txtPasswordSignUpInputMethodTextChanged

  private void txtPasswordSignUpPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPasswordSignUpPropertyChange

  }//GEN-LAST:event_txtPasswordSignUpPropertyChange

  private void NewProjectButtonPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProjectButtonPVActionPerformed
		cardLayoutPV.show(pnlCardPV, "NewProject");
  }//GEN-LAST:event_NewProjectButtonPVActionPerformed

  private void CreateProjectBTNNPPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateProjectBTNNPPVActionPerformed
		ProjectManager projectManager = new ProjectManager();

		if (ProjectNameTXTNPPV.getText().equals("")) {
			ErrorLabelNPPV.setText("Please Enter the Project Title");
		} else if (ProjectDescriptionLabelNPPV.getText().equals("")) {
			ErrorLabelNPPV.setText("Please Enter the Project Description");
		} else if (ProjectNameTXTNPPV.getText().length() > 100) {
			ErrorLabelNPPV.setText("Title is too long");
		} else if (ProjectDescriptionLabelNPPV.getText().length() > 300) {
			ErrorLabelNPPV.setText("Desription is too long");
		} else if (projectManager.createProject(ProjectNameTXTNPPV.getText(), DesriptionTextAreaNPPV.getText(), currentUser) <= -1) {
			cardLayoutPV.show(pnlCardPV, "ProjectViewPV");
			refreshProjectView();
			JOptionPane.showMessageDialog(this,
							"Successfully Created Project ✔"
							+ "\nClick Refresh to see it"
			);
		}
  }//GEN-LAST:event_CreateProjectBTNNPPVActionPerformed

  private void RefreshButtonPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonPVActionPerformed
		pnlCardPV.repaint();
		refreshProjectView();
		pnlCardPV.repaint();
  }//GEN-LAST:event_RefreshButtonPVActionPerformed

  private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
		cardLayoutPV.show(pnlCardPV, "NewProject");
		refreshProjectView();
		cardLayoutPV.show(pnlCardPV, "ProjectViewPV");
  }//GEN-LAST:event_BackButtonActionPerformed

  private void AccountSetButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountSetButtonsActionPerformed
		cardLayoutPV.show(pnlCardPV, "AccountSettings");
  }//GEN-LAST:event_AccountSetButtonsActionPerformed

  private void DeleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountButtonActionPerformed
		UserManager userManager = new UserManager();
		userManager.deleteAccount(currentUsername);
  }//GEN-LAST:event_DeleteAccountButtonActionPerformed

  private void ProjectViewCardPVComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ProjectViewCardPVComponentAdded

  }//GEN-LAST:event_ProjectViewCardPVComponentAdded

  private void ProjectViewCardPVComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProjectViewCardPVComponentShown

  }//GEN-LAST:event_ProjectViewCardPVComponentShown

  private void AccounSettingsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccounSettingsBackButtonActionPerformed
		refreshProjectView();
		cardLayoutPV.show(pnlCardPV, "ProjectViewPV");
  }//GEN-LAST:event_AccounSettingsBackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		new Help().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// Set Look and Feel Settings
				LafManager.enableLogging(true);
				LafManager.setTheme(new DarculaTheme());
				LafManager.install();

				// Form Creation
				new MainForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AccounSettingsBackButton;
    private javax.swing.JLabel AccountIcon;
    private javax.swing.JLabel AccountName;
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JButton AccountSetButtons;
    private javax.swing.JPanel AccountSettingToolbar;
    private javax.swing.JPanel AccountSettingsPanel;
    private javax.swing.JLabel AccountUsername;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CreateProjectBTNNPPV;
    private javax.swing.JButton DeleteAccountButton;
    private javax.swing.JTextArea DesriptionTextAreaNPPV;
    private javax.swing.JLabel ErrorLabelNPPV;
    private javax.swing.JLabel ErrorText;
    private javax.swing.JButton NewProjectButtonPV;
    private javax.swing.JPanel NewProjectDetailsPV;
    private javax.swing.JPanel NewProjectViewPV;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel ProjectDescriptionLabelNPPV;
    private javax.swing.JLabel ProjectNameLabelNPPV;
    private javax.swing.JTextField ProjectNameTXTNPPV;
    private javax.swing.JScrollPane ProjectScrollViewPV;
    private javax.swing.JPanel ProjectViewCardPV;
    private javax.swing.JPanel ProjectViewToolBarPV;
    private javax.swing.JButton RefreshButtonPV;
    private javax.swing.JPanel ScrollViewPV;
    private javax.swing.JSeparator SeperatorNPPV;
    private javax.swing.JButton SignInButtonLogPNL;
    private javax.swing.JButton SignUpInsteadButtonLogPNL;
    private javax.swing.JScrollPane TextScrollNPPV;
    private javax.swing.JPanel ToolBarNPPV;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameText;
    private javax.swing.JLabel UsernameText2;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JButton btnSignUpInsteadSignUp;
    private javax.swing.JButton btnSignUpSignUp;
    private com.toedter.calendar.JDateChooser dcDOBSignUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfirmPasswordSignUp;
    private javax.swing.JLabel lblDOBSignUP;
    private javax.swing.JLabel lblEmailSignUp;
    private javax.swing.JLabel lblErrorSignUp;
    private javax.swing.JLabel lblFirstNameSignUp;
    private javax.swing.JLabel lblPasswordSignUp;
    private javax.swing.JLabel lblPasswordStrengthSignUp;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblSurnameSignUp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsernameSignUp;
    private javax.swing.JProgressBar pbarPasswordStrengthSignUp;
    private javax.swing.JPanel pnlButtonContainer;
    public static javax.swing.JPanel pnlCardPV;
    private javax.swing.JPanel pnlInitial;
    private javax.swing.JPanel pnlInitialContainer;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JSplitPane pnlMainSplit;
    private javax.swing.JPanel pnlProjectList;
    private javax.swing.JPanel pnlSidePane;
    private javax.swing.JPanel pnlSignIn;
    private javax.swing.JPanel pnlSignInContainer;
    private javax.swing.JPanel pnlSignUp;
    private javax.swing.JPanel pnlSignUpContainer;
    private javax.swing.JPanel pnlTitleContainer;
    private javax.swing.JPasswordField txtConfirmPasswordSignUp;
    private javax.swing.JTextField txtEmailSignUp;
    private javax.swing.JTextField txtFirstNameSignUp;
    private javax.swing.JPasswordField txtPasswordSignUp;
    private javax.swing.JTextField txtSurnameSignUp;
    private javax.swing.JTextField txtUsernameSignUp;
    // End of variables declaration//GEN-END:variables
}
